#
# Welcome to the HotBlocks configuration settings
#
# - The configuration is not simple, so please read the documentation first.
# -
# - Please see our Github Wiki
# -      https://github.com/Kirastur/HotBlocks/wiki
# -
# - For support you can contact us at discord.
# -      A link to discord can be found on the Github Wiki
# -
# - For a quick test do the following (assuming your world is called "world"):
# -   1.  enter "/hotblock enable world" on the server console
# -   2.  Place a blue concrete block on the ground
# -   3. Jump onto this block
# - As a result the block changes its color to red imediatly and vanishs 2 seconds later


# startup
# 
# - Global settings only read at systemstart
startup:

   # Use Passive mode
   #
   # - In passive mode the plugin engine is not initialized,
   # - only the Java objects are avail.
   # - You had to instanciate your own orchestratator
   # - and regsiter it as API.
   # - Use this option only if you customize the Java objects itself.
   passiveMode: false
   
   # Debug
   #
   # - Enable Debug Messages to server console
   debug: false
   
   # autostart
   #
   # - Normally you start HotBlocks for a specific world 
   # - when your start your game by entering:
   # -    /hotblocks enable <worldname>
   # - 
   # - But in some scenarios you want to start HotBlocks
   # - with serverboot. Here you can enter a list of
   # - worldnames which should be Hotblocks-enabled directly from the beginning.
   # - 
   # - This list is checked only once at serverstart.
#  autostart:
#      - world
#      - demoworld1
#      - demoworld2
   
# rules
# 
# - Here you can define your own rules for block modifications
# - You can safely delete the demo-rules here.   
rules:
    ConcreteBlue:
        fromMaterial: BLUE_CONCRETE
        toMaterial: RED_CONCRETE
        lifetime: 1
        points: 1
        continueModify: true
       
    ConcreteRed:
        fromMaterial: RED_CONCRETE
        lifetime: 40
        sound: BLOCK_STONE_BREAK
        listener: Cascade
